set_targetdir(".out")

target("fist-three")
    set_kind("binary")
    set_languages("cxx17")
    add_files("first/three.cpp")
    add_includedirs("first")

target("fist-complex")
    set_kind("binary")
    set_languages("cxx17")
    add_files("first/complex.cpp")
    add_includedirs("first")

target("second-delete")
    set_kind("binary")
    set_languages("cxx17")
    add_files("second/delete_key.cpp")

target("second-list")
    set_kind("binary")
    set_languages("cxx17")
    add_files("second/List.cpp")

target("third-10to2")
    set_kind("binary")
    set_languages("cxx17")
    add_files("third/10to2.cpp")
    add_includedirs("third")

target("third-cal")
    set_kind("binary")
    set_languages("cxx17")
    add_files("third/calculate.cpp")
    add_includedirs("third")

target("fourth-1-string")
    set_kind("binary")
    set_languages("cxx17")
    add_files("fourth/string.cpp")
    add_includedirs("fourth")
    add_includedirs("fourth-2")

target("fourth-1-kmp")
    set_kind("binary")
    set_languages("cxx17")
    add_files("fourth/kmp.cpp")

target("fourth-2")
    set_kind("binary")
    set_languages("cxx17")
    add_files("fourth-2/string.cpp")
    add_includedirs("fourth")
    add_includedirs("fourth-2")